name: Deploy Repoter

on:
  push:
    paths:
      - lambdas/report/**
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18'
      - name: Add known hosts
        env:
          HOST: ${{ secrets.HOST }}
        run: |
          mkdir -p /home/runner/.ssh/
          ssh-keyscan $HOST > /home/runner/.ssh/known_hosts
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build and Deploy
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.OS_USER }}
        run: |
          cd lambdas/report
          go mod tidy
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main 
          scp main report.html $USER@$HOST:/home/ubuntu/reporter/