name: Deploy Backend

on:
  push:
    paths:
      - api/**
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18'
      - name: Add known hosts
        env:
          HOST: ${{ secrets.HOST }}
        run: |
          mkdir -p /home/runner/.ssh/
          ssh-keyscan $HOST > /home/runner/.ssh/known_hosts
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build and Deploy
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.OS_USER }}
        run: |
          cd api/cmd/afiyet
          go mod tidy
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-X main.CommitSHA=$(git rev-parse HEAD)" -o main
          scp main $USER@$HOST:/home/ubuntu/app/new
          ssh $USER@$HOST /home/ubuntu/app/deploy.sh
